---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http4s-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: http4s 
    spec:
      containers:
      - name: try-http4s 
        image: sebastianharko/try-http4s:0.1
        imagePullPolicy: Always
        env: 
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080 
        resources:
          requests:
            cpu: 5
            memory: 5Gi
          limits:
            cpu: 5
            memory: 5Gi
---
kind: Service
apiVersion: v1
metadata:
 name: http4s-service
spec:
  selector:
    app: http4s 
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080 
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
